heat_template_version: rocky

parameters:
  NetName:
    description: NetName
    type: string
    default: network

  RouterName:
    description: RouterName
    type: string
    default: router
    
  SubnetName:
    description: SubnetName
    type: string
    default: subnet1
    
  PrivateSubnetCidr:
    description: PrivateSubnetCidr
    type: string
    default: 10.0.0.0/24

resources:
  Net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: NetName }
      admin_state_up: True
      shared: False

  PrivateSubnet:
    type: OS::Neutron::Subnet
    properties:
      name: { get_param: SubnetName }
      cidr: { get_param: PrivateSubnetCidr }
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4
      enable_dhcp: True
      network: { get_resource: Net }

  Router:
    type: OS::Neutron::Router
    properties:
      name: { get_param: RouterName }
      admin_state_up: True
      external_gateway_info: {
         enable_snat: True,
         network: ext-net
      }

  RouterPort:
    type: OS::Neutron::Port
    properties:
      name: RouterPort
      fixed_ips:
        - ip_address: 10.0.0.1
      network: { get_resource: Net }
       
  RouterInterface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: Router }
      port: { get_resource: RouterPort }
